"""Agrega campos cortos de carnet al modelo Center

Revision ID: 413ee2f4299c
Revises: 09f764225ecc
Create Date: 2026-04-04 09:08:52.339309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413ee2f4299c'
down_revision: Union[str, Sequence[str], None] = '09f764225ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('card_philosophy', sa.String(length=255), nullable=True))
    op.add_column('centers', sa.Column('card_mission', sa.String(length=255), nullable=True))
    op.add_column('centers', sa.Column('card_vision', sa.String(length=255), nullable=True))
    op.add_column('centers', sa.Column('card_values', sa.String(length=255), nullable=True))
    op.add_column('centers', sa.Column('card_footer_text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'card_footer_text')
    op.drop_column('centers', 'card_values')
    op.drop_column('centers', 'card_vision')
    op.drop_column('centers', 'card_mission')
    op.drop_column('centers', 'card_philosophy')
    # ### end Alembic commands ###
