"""add card design config to centers

Revision ID: 420c14ec7d11
Revises: 95298556ad4a
Create Date: 2026-04-12 08:35:01.784898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420c14ec7d11'
down_revision: Union[str, Sequence[str], None] = '95298556ad4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('card_design_key', sa.String(length=100), server_default='classic_green_v1', nullable=False))
    op.add_column('centers', sa.Column('show_full_card_identity', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'show_full_card_identity')
    op.drop_column('centers', 'card_design_key')
    # ### end Alembic commands ###
