"""add billing invoices table

Revision ID: 5f9f370964e8
Revises: 420c14ec7d11
Create Date: 2026-04-15 10:23:53.181079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9f370964e8'
down_revision: Union[str, Sequence[str], None] = '420c14ec7d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('concept', sa.String(length=150), nullable=False),
    sa.Column('card_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_center_id'), 'billing_invoices', ['center_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_due_date'), 'billing_invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_billing_invoices_id'), 'billing_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_invoice_number'), 'billing_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_billing_invoices_issue_date'), 'billing_invoices', ['issue_date'], unique=False)
    op.create_index(op.f('ix_billing_invoices_status'), 'billing_invoices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_invoices_status'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_issue_date'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_invoice_number'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_due_date'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_center_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    # ### end Alembic commands ###
