"""create guardians table

Revision ID: 71bbf1215d12
Revises: 39d920885b4e
Create Date: 2026-04-01 03:58:12.022425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bbf1215d12'
down_revision: Union[str, Sequence[str], None] = '39d920885b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('student_code', sa.String(length=50), nullable=False),
    sa.Column('minerd_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_id', 'school_year_id', 'student_code', name='uq_student_center_year_code')
    )
    op.create_index(op.f('ix_students_center_id'), 'students', ['center_id'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_minerd_id'), 'students', ['minerd_id'], unique=False)
    op.create_index(op.f('ix_students_school_year_id'), 'students', ['school_year_id'], unique=False)
    op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=False)
    op.create_table('guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_id'), 'guardians', ['id'], unique=False)
    op.create_index(op.f('ix_guardians_student_id'), 'guardians', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardians_student_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_id'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_students_student_code'), table_name='students')
    op.drop_index(op.f('ix_students_school_year_id'), table_name='students')
    op.drop_index(op.f('ix_students_minerd_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_center_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
