"""create cards table

Revision ID: 74e28f4a36ff
Revises: 71bbf1215d12
Create Date: 2026-04-01 04:05:06.263060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e28f4a36ff'
down_revision: Union[str, Sequence[str], None] = '71bbf1215d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('card_code', sa.String(length=100), nullable=False),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_code', name='uq_cards_card_code'),
    sa.UniqueConstraint('qr_token', name='uq_cards_qr_token')
    )
    op.create_index(op.f('ix_cards_card_code'), 'cards', ['card_code'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_qr_token'), 'cards', ['qr_token'], unique=False)
    op.create_index(op.f('ix_cards_student_id'), 'cards', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_student_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_qr_token'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_code'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
