"""create attendance daily summary table

Revision ID: 796da93e2607
Revises: 7b14c10e4ef9
Create Date: 2026-04-01 04:17:09.848129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796da93e2607'
down_revision: Union[str, Sequence[str], None] = '7b14c10e4ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_daily_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('has_excuse', sa.Boolean(), nullable=False),
    sa.Column('excuse_note', sa.String(length=255), nullable=True),
    sa.Column('first_entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes_late', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_student_date')
    )
    op.create_index(op.f('ix_attendance_daily_summary_date'), 'attendance_daily_summary', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_daily_summary_id'), 'attendance_daily_summary', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_daily_summary_status'), 'attendance_daily_summary', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_daily_summary_student_id'), 'attendance_daily_summary', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_daily_summary_student_id'), table_name='attendance_daily_summary')
    op.drop_index(op.f('ix_attendance_daily_summary_status'), table_name='attendance_daily_summary')
    op.drop_index(op.f('ix_attendance_daily_summary_id'), table_name='attendance_daily_summary')
    op.drop_index(op.f('ix_attendance_daily_summary_date'), table_name='attendance_daily_summary')
    op.drop_table('attendance_daily_summary')
    # ### end Alembic commands ###
