"""create attendance_events table

Revision ID: 7b14c10e4ef9
Revises: 74e28f4a36ff
Create Date: 2026-04-01 04:09:33.653590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b14c10e4ef9'
down_revision: Union[str, Sequence[str], None] = '74e28f4a36ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_events_card_id'), 'attendance_events', ['card_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_event_time'), 'attendance_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_attendance_events_event_type'), 'attendance_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_attendance_events_id'), 'attendance_events', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_events_status'), 'attendance_events', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_events_student_id'), 'attendance_events', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_events_student_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_status'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_event_type'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_event_time'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_card_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    # ### end Alembic commands ###
