"""create center attendance days table

Revision ID: 8ffb98f60c13
Revises: d10c09f89b53
Create Date: 2026-04-01 04:36:35.160982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffb98f60c13'
down_revision: Union[str, Sequence[str], None] = 'd10c09f89b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_attendance_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_workday', sa.Boolean(), nullable=False),
    sa.Column('had_attendance_activity', sa.Boolean(), nullable=False),
    sa.Column('possible_no_school_day', sa.Boolean(), nullable=False),
    sa.Column('possible_early_dismissal', sa.Boolean(), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('total_exits', sa.Integer(), nullable=False),
    sa.Column('total_present', sa.Integer(), nullable=False),
    sa.Column('total_late', sa.Integer(), nullable=False),
    sa.Column('total_absent', sa.Integer(), nullable=False),
    sa.Column('total_with_excuse', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_id', 'school_year_id', 'date', name='uq_center_school_year_date')
    )
    op.create_index(op.f('ix_center_attendance_days_center_id'), 'center_attendance_days', ['center_id'], unique=False)
    op.create_index(op.f('ix_center_attendance_days_date'), 'center_attendance_days', ['date'], unique=False)
    op.create_index(op.f('ix_center_attendance_days_id'), 'center_attendance_days', ['id'], unique=False)
    op.create_index(op.f('ix_center_attendance_days_school_year_id'), 'center_attendance_days', ['school_year_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_center_attendance_days_school_year_id'), table_name='center_attendance_days')
    op.drop_index(op.f('ix_center_attendance_days_id'), table_name='center_attendance_days')
    op.drop_index(op.f('ix_center_attendance_days_date'), table_name='center_attendance_days')
    op.drop_index(op.f('ix_center_attendance_days_center_id'), table_name='center_attendance_days')
    op.drop_table('center_attendance_days')
    # ### end Alembic commands ###
