"""create school_years table

Revision ID: a4ceba24cc86
Revises: 4d574fa28304
Create Date: 2026-04-01 03:32:42.241867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ceba24cc86'
down_revision: Union[str, Sequence[str], None] = '4d574fa28304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('center_id', 'name', name='uq_school_year_center_name')
    )
    op.create_index(op.f('ix_school_years_center_id'), 'school_years', ['center_id'], unique=False)
    op.create_index(op.f('ix_school_years_id'), 'school_years', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_years_id'), table_name='school_years')
    op.drop_index(op.f('ix_school_years_center_id'), table_name='school_years')
    op.drop_table('school_years')
    # ### end Alembic commands ###
