"""create center schedules table

Revision ID: d10c09f89b53
Revises: 796da93e2607
Create Date: 2026-04-01 04:31:24.285652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10c09f89b53'
down_revision: Union[str, Sequence[str], None] = '796da93e2607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.Time(), nullable=False),
    sa.Column('exit_time', sa.Time(), nullable=False),
    sa.Column('workdays', sa.String(length=50), nullable=False),
    sa.Column('late_tolerance_minutes', sa.Integer(), nullable=False),
    sa.Column('absence_cutoff_time', sa.Time(), nullable=False),
    sa.Column('early_dismissal_threshold_time', sa.Time(), nullable=False),
    sa.Column('minimum_attendance_for_school_day', sa.Integer(), nullable=False),
    sa.Column('early_dismissal_percentage_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_center_schedules_center_id'), 'center_schedules', ['center_id'], unique=True)
    op.create_index(op.f('ix_center_schedules_id'), 'center_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_center_schedules_id'), table_name='center_schedules')
    op.drop_index(op.f('ix_center_schedules_center_id'), table_name='center_schedules')
    op.drop_table('center_schedules')
    # ### end Alembic commands ###
