"""create authorized exits table

Revision ID: d68b4877a0cd
Revises: d60799fe77b8
Create Date: 2026-04-01 08:17:13.879047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68b4877a0cd'
down_revision: Union[str, Sequence[str], None] = 'd60799fe77b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_exits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('authorized_by_name', sa.String(length=150), nullable=False),
    sa.Column('authorized_by_role', sa.String(length=100), nullable=False),
    sa.Column('released_to_name', sa.String(length=150), nullable=True),
    sa.Column('released_to_relationship', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('requires_guardian_pickup', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorized_exits_center_id'), 'authorized_exits', ['center_id'], unique=False)
    op.create_index(op.f('ix_authorized_exits_exit_time'), 'authorized_exits', ['exit_time'], unique=False)
    op.create_index(op.f('ix_authorized_exits_id'), 'authorized_exits', ['id'], unique=False)
    op.create_index(op.f('ix_authorized_exits_school_year_id'), 'authorized_exits', ['school_year_id'], unique=False)
    op.create_index(op.f('ix_authorized_exits_student_id'), 'authorized_exits', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorized_exits_student_id'), table_name='authorized_exits')
    op.drop_index(op.f('ix_authorized_exits_school_year_id'), table_name='authorized_exits')
    op.drop_index(op.f('ix_authorized_exits_id'), table_name='authorized_exits')
    op.drop_index(op.f('ix_authorized_exits_exit_time'), table_name='authorized_exits')
    op.drop_index(op.f('ix_authorized_exits_center_id'), table_name='authorized_exits')
    op.drop_table('authorized_exits')
    # ### end Alembic commands ###
